#datasource: bag # set bag for rosbags or folder of
image_topics:
    - /cam/cam0 #if datasource != 0, set null
camera_topics:
    - /imu/imu  #if datasource != 0, set null
#- folder: null
    
image_scale_factor:
- 1
- 2
optical_flow_type: dense


